services:
  - type: web
    name: hexa-tv
    env: static
    buildCommand: echo "No build needed - static files"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
